// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/yjs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_proto_yjs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{0}
}

func (x *TestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_proto_yjs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{1}
}

func (x *TestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_yjs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{2}
}

type SyncV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docname       string                 `protobuf:"bytes,1,opt,name=docname,proto3" json:"docname,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncV1Request) Reset() {
	*x = SyncV1Request{}
	mi := &file_proto_yjs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncV1Request) ProtoMessage() {}

func (x *SyncV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncV1Request.ProtoReflect.Descriptor instead.
func (*SyncV1Request) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{3}
}

func (x *SyncV1Request) GetDocname() string {
	if x != nil {
		return x.Docname
	}
	return ""
}

func (x *SyncV1Request) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type SyncV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncV1Response) Reset() {
	*x = SyncV1Response{}
	mi := &file_proto_yjs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncV1Response) ProtoMessage() {}

func (x *SyncV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncV1Response.ProtoReflect.Descriptor instead.
func (*SyncV1Response) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{4}
}

func (x *SyncV1Response) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type WebsocketMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docname       string                 `protobuf:"bytes,1,opt,name=docname,proto3" json:"docname,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessageRequest) Reset() {
	*x = WebsocketMessageRequest{}
	mi := &file_proto_yjs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessageRequest) ProtoMessage() {}

func (x *WebsocketMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessageRequest.ProtoReflect.Descriptor instead.
func (*WebsocketMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{5}
}

func (x *WebsocketMessageRequest) GetDocname() string {
	if x != nil {
		return x.Docname
	}
	return ""
}

func (x *WebsocketMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WebsocketMessageRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type WebsocketMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessageResponse) Reset() {
	*x = WebsocketMessageResponse{}
	mi := &file_proto_yjs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessageResponse) ProtoMessage() {}

func (x *WebsocketMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessageResponse.ProtoReflect.Descriptor instead.
func (*WebsocketMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{6}
}

func (x *WebsocketMessageResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docname       string                 `protobuf:"bytes,1,opt,name=docname,proto3" json:"docname,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_yjs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{7}
}

func (x *SyncRequest) GetDocname() string {
	if x != nil {
		return x.Docname
	}
	return ""
}

func (x *SyncRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type SyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocMessage       []byte                 `protobuf:"bytes,1,opt,name=doc_message,json=docMessage,proto3" json:"doc_message,omitempty"`
	AwarenessMessage []byte                 `protobuf:"bytes,2,opt,name=awareness_message,json=awarenessMessage,proto3" json:"awareness_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_yjs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{8}
}

func (x *SyncResponse) GetDocMessage() []byte {
	if x != nil {
		return x.DocMessage
	}
	return nil
}

func (x *SyncResponse) GetAwarenessMessage() []byte {
	if x != nil {
		return x.AwarenessMessage
	}
	return nil
}

type RemoveClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docname       string                 `protobuf:"bytes,1,opt,name=docname,proto3" json:"docname,omitempty"`
	Origins       []string               `protobuf:"bytes,2,rep,name=origins,proto3" json:"origins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientRequest) Reset() {
	*x = RemoveClientRequest{}
	mi := &file_proto_yjs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientRequest) ProtoMessage() {}

func (x *RemoveClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yjs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientRequest.ProtoReflect.Descriptor instead.
func (*RemoveClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_yjs_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveClientRequest) GetDocname() string {
	if x != nil {
		return x.Docname
	}
	return ""
}

func (x *RemoveClientRequest) GetOrigins() []string {
	if x != nil {
		return x.Origins
	}
	return nil
}

var File_proto_yjs_proto protoreflect.FileDescriptor

const file_proto_yjs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/yjs.proto\x12\x03yjs\"'\n" +
	"\vTestRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fTestResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"A\n" +
	"\rSyncV1Request\x12\x18\n" +
	"\adocname\x18\x01 \x01(\tR\adocname\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\"*\n" +
	"\x0eSyncV1Response\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"e\n" +
	"\x17WebsocketMessageRequest\x12\x18\n" +
	"\adocname\x18\x01 \x01(\tR\adocname\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\"E\n" +
	"\x18WebsocketMessageResponse\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"?\n" +
	"\vSyncRequest\x12\x18\n" +
	"\adocname\x18\x01 \x01(\tR\adocname\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\"\\\n" +
	"\fSyncResponse\x12\x1f\n" +
	"\vdoc_message\x18\x01 \x01(\fR\n" +
	"docMessage\x12+\n" +
	"\x11awareness_message\x18\x02 \x01(\fR\x10awarenessMessage\"I\n" +
	"\x13RemoveClientRequest\x12\x18\n" +
	"\adocname\x18\x01 \x01(\tR\adocname\x12\x18\n" +
	"\aorigins\x18\x02 \x03(\tR\aorigins2\xba\x02\n" +
	"\x03YJS\x12+\n" +
	"\x04Test\x12\x10.yjs.TestRequest\x1a\x11.yjs.TestResponse\x12\x1f\n" +
	"\x05Close\x12\n" +
	".yjs.Empty\x1a\n" +
	".yjs.Empty\x12O\n" +
	"\x10WebsocketMessage\x12\x1c.yjs.WebsocketMessageRequest\x1a\x1d.yjs.WebsocketMessageResponse\x121\n" +
	"\x06SyncV1\x12\x12.yjs.SyncV1Request\x1a\x13.yjs.SyncV1Response\x12+\n" +
	"\x04Sync\x12\x10.yjs.SyncRequest\x1a\x11.yjs.SyncResponse\x124\n" +
	"\fRemoveClient\x12\x18.yjs.RemoveClientRequest\x1a\n" +
	".yjs.EmptyB\tZ\a./protob\x06proto3"

var (
	file_proto_yjs_proto_rawDescOnce sync.Once
	file_proto_yjs_proto_rawDescData []byte
)

func file_proto_yjs_proto_rawDescGZIP() []byte {
	file_proto_yjs_proto_rawDescOnce.Do(func() {
		file_proto_yjs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yjs_proto_rawDesc), len(file_proto_yjs_proto_rawDesc)))
	})
	return file_proto_yjs_proto_rawDescData
}

var file_proto_yjs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_yjs_proto_goTypes = []any{
	(*TestRequest)(nil),              // 0: yjs.TestRequest
	(*TestResponse)(nil),             // 1: yjs.TestResponse
	(*Empty)(nil),                    // 2: yjs.Empty
	(*SyncV1Request)(nil),            // 3: yjs.SyncV1Request
	(*SyncV1Response)(nil),           // 4: yjs.SyncV1Response
	(*WebsocketMessageRequest)(nil),  // 5: yjs.WebsocketMessageRequest
	(*WebsocketMessageResponse)(nil), // 6: yjs.WebsocketMessageResponse
	(*SyncRequest)(nil),              // 7: yjs.SyncRequest
	(*SyncResponse)(nil),             // 8: yjs.SyncResponse
	(*RemoveClientRequest)(nil),      // 9: yjs.RemoveClientRequest
}
var file_proto_yjs_proto_depIdxs = []int32{
	0, // 0: yjs.YJS.Test:input_type -> yjs.TestRequest
	2, // 1: yjs.YJS.Close:input_type -> yjs.Empty
	5, // 2: yjs.YJS.WebsocketMessage:input_type -> yjs.WebsocketMessageRequest
	3, // 3: yjs.YJS.SyncV1:input_type -> yjs.SyncV1Request
	7, // 4: yjs.YJS.Sync:input_type -> yjs.SyncRequest
	9, // 5: yjs.YJS.RemoveClient:input_type -> yjs.RemoveClientRequest
	1, // 6: yjs.YJS.Test:output_type -> yjs.TestResponse
	2, // 7: yjs.YJS.Close:output_type -> yjs.Empty
	6, // 8: yjs.YJS.WebsocketMessage:output_type -> yjs.WebsocketMessageResponse
	4, // 9: yjs.YJS.SyncV1:output_type -> yjs.SyncV1Response
	8, // 10: yjs.YJS.Sync:output_type -> yjs.SyncResponse
	2, // 11: yjs.YJS.RemoveClient:output_type -> yjs.Empty
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_yjs_proto_init() }
func file_proto_yjs_proto_init() {
	if File_proto_yjs_proto != nil {
		return
	}
	file_proto_yjs_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yjs_proto_rawDesc), len(file_proto_yjs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_yjs_proto_goTypes,
		DependencyIndexes: file_proto_yjs_proto_depIdxs,
		MessageInfos:      file_proto_yjs_proto_msgTypes,
	}.Build()
	File_proto_yjs_proto = out.File
	file_proto_yjs_proto_goTypes = nil
	file_proto_yjs_proto_depIdxs = nil
}
